### PR TITLE
Add link to introduction.

### PR DESCRIPTION
**Pull request by arokem**
Need to run this on my machine, to generate README. 

Would be nice to set Travis up to do that!

### CODE REVIEW

**Comment by arokem** [comment]
Turns out I don't have write access to this repo. @tyarkoni : could you please merge this (and/or add me to the contributors?)

**Comment by tyarkoni** [comment]
Merged, but you're already in the contributor list. Will check permissions.

**Comment by arokem** [comment]
I might not have clicked on the invitation. It's one of the most annoying
features of GitHub. You have to click on a link in an email to become a
contributor, even after someone else adds you.

**Comment by arokem** [comment]
Yeah - I should be good to go now.

**Pull request merged**
